/**
 * Building footprint helpers — derived from the pathing manifest.
 *
 * The authoritative source is `helpers/buildingPathing.json`, generated by
 * `tools/parse-building-pathing.js` from WC3's `PathTextures\*.tga` (extracted
 * via CASC). There is no fallback heuristic — buildings without a manifest
 * entry will throw, which is intentional: it forces the data pipeline to be
 * complete and correct.
 */

const manifest = require('./buildingPathing.json');

function getBuildingWpmFootprint (itemId) {
  const entry = manifest.buildings[itemId];
  if (!entry) {
    throw new Error('No pathing manifest entry for itemId="' + itemId +
                    '". Re-run tools/parse-building-pathing.js.');
  }
  return entry.widthCells;  // returned for square-footprint callers (placement heuristics)
}

function getBuildingTileFootprint (itemId) {
  const entry = manifest.buildings[itemId];
  if (!entry) {
    throw new Error('No pathing manifest entry for itemId="' + itemId + '"');
  }
  return entry.widthCells / 4;
}

function getBuildingFootprintDims (itemId) {
  const entry = manifest.buildings[itemId];
  if (!entry) {
    throw new Error('No pathing manifest entry for itemId="' + itemId + '"');
  }
  return {
    widthCells: entry.widthCells,
    heightCells: entry.heightCells,
    widthTiles: entry.widthCells / 4,
    heightTiles: entry.heightCells / 4
  };
}

module.exports = {
  getBuildingWpmFootprint,
  getBuildingTileFootprint,
  getBuildingFootprintDims
};
