// GENERATED by tools/build-item-classes.js — do not edit by hand.
//
// Which shop items are SPENT rather than KEPT, for the build card's Bought row.
// Derived from helpers/mappings.js (itemAbilityData.category) with
// helpers/dropTables.json (items[].class) as the fallback; see the generator
// for the precedence rules and the one known imprecision (charged 'active'
// items are classed kept).
//
// Only the consumed set is listed. Anything absent — including an id this
// build has never seen — is kept, which is the safe default: an unclassified
// artifact belongs beside the permanents.
//
// 67 ids: 50 from itemAbilityData, 17 from dropTables.

(function () {
  'use strict';

  window.ItemClasses = {
    consumed: {
      "amrc": 1, "ankh": 1, "dust": 1, "gfor": 1, "gobm": 1, "gold": 1,
      "gomn": 1, "guvi": 1, "hlst": 1, "hslv": 1, "infs": 1, "lmbr": 1,
      "lure": 1, "manh": 1, "mnst": 1, "moon": 1, "pams": 1, "pclr": 1,
      "pdiv": 1, "pghe": 1, "pgin": 1, "pgma": 1, "phea": 1, "pinv": 1,
      "plcl": 1, "pman": 1, "pnvl": 1, "pnvu": 1, "pomn": 1, "pres": 1,
      "pspd": 1, "rdis": 1, "rhe1": 1, "rhe2": 1, "rhe3": 1, "rma2": 1,
      "rman": 1, "rre1": 1, "rre2": 1, "rreb": 1, "rres": 1, "rspd": 1,
      "rspl": 1, "rsps": 1, "rwat": 1, "sand": 1, "shas": 1, "shea": 1,
      "skul": 1, "sman": 1, "spro": 1, "sreg": 1, "sror": 1, "srrc": 1,
      "stwp": 1, "tdex": 1, "tdx2": 1, "texp": 1, "tgxp": 1, "tin2": 1,
      "tint": 1, "tkno": 1, "tpow": 1, "tret": 1, "tst2": 1, "tstr": 1,
      "vamp": 1
    },

    isConsumed (itemId) {
      return !!(itemId && this.consumed[itemId]);
    }
  };
})();
