const utils = require("../helpers/utils"),
      PathFinder = require("./PathFinder"),
      CollisionWorld = require("./CollisionWorld");

const Unit = require("./Unit");

// Building pathing manifest (generated by tools/parse-building-pathing.js).
// Bundled into the browser parser via esbuild's JSON support. Required —
// missing manifest crashes the parser on World construction, which is the
// correct behaviour since the data is mandatory.
const buildingPathingManifest = require("../helpers/buildingPathing.json");

const {
  NEUTRAL_PLAYER_ID,
  NEUTRAL_PLAYER_SLOT,
  NEUTRAL_PLAYER_TEAM
} = require("../helpers/mappings");

// Owner-id predicate used by the battle registry. Neutral creeps live under
// NEUTRAL_PLAYER_ID and shouldn't open PvP battles — those are handled by
// NeutralGroup. Anything outside the real-player range (id ≥ 24) is also
// considered non-player (custom/observer slots).
const _isNonPlayerOwner = (ownerPlayerId) => {
  if (ownerPlayerId == null) return true;
  if (Number(ownerPlayerId) === NEUTRAL_PLAYER_ID) return true;
  if (Number(ownerPlayerId) >= 24) return true;
  return false;
};

const World = class {
  constructor (eventTimer) {
    this.droppedItems = [];
    this.unknownObjects = [];
    this.eventTimer = eventTimer;

    this.playerData = {};
    this.neutralShops = [];

    this.neutralGroups = {};
    this.neutralGroupTree = null;

    this.gridData = null;

    // Cross-player unit lookup. Keyed by "objId1|objId2".
    // Populated via Unit.bindToWorld() once an owning Player attaches a unit.
    // Used by BattleDetector (Phase 1) to resolve enemy targets — neither
    // Player.findUnitByObjectId (own units only) nor World.findNeutralByObjectIds
    // covers cross-player resolution today.
    this.unitRegistry = new Map();

    // Populated by BattleDetector post-process; surfaced via utils.buildOutputObject.
    this.battles = null;
    this.battleStats = null;
  }

  // Registry helpers — purely additive index over units the parser has already
  // built into playerData/units. Owning Player calls registerUnit (via
  // Unit.bindToWorld → on registerObjectIds). PlayerActions.destroyUnit calls
  // unregisterUnit. Allies share a teamId; "enemy" is decided downstream so
  // this registry stays cheap (no team math here).
  _registryKey (objectId1, objectId2) {
    return `${objectId1}|${objectId2}`;
  }

  registerUnit (unit, ownerPlayerId, ownerTeamId) {
    if (unit == null || unit.objectId1 == null || unit.objectId2 == null) {
      return;
    }
    this.unitRegistry.set(
      this._registryKey(unit.objectId1, unit.objectId2),
      { unit, ownerPlayerId, ownerTeamId: (ownerTeamId == null ? null : ownerTeamId) }
    );
  }

  unregisterUnit (unit) {
    if (unit == null || unit.objectId1 == null || unit.objectId2 == null) {
      return;
    }
    this.unitRegistry.delete(this._registryKey(unit.objectId1, unit.objectId2));
  }

  findUnitByObjectIds (objectId1, objectId2) {
    return this.unitRegistry.get(this._registryKey(objectId1, objectId2)) || null;
  }

  // Returns { unit, ownerPlayerId, ownerTeamId } only when the resolved owner
  // is on a DIFFERENT TEAM from the actor AND is a real player. Same-team
  // (ally) hits and neutral/non-player hits return null — heals on allies
  // shouldn't open PvP battles. Callers wanting neutral lookups should use
  // findNeutralByObjectIds; own units use Player.findUnitByObjectId.
  //
  // actorTeamId is OPTIONAL for back-compat. When omitted, falls back to the
  // weaker "different player" check (this is what 1v1 used to do — each
  // player is their own team anyway). Pass it for correct team-game behavior.
  findEnemyByObjectIds (objectId1, objectId2, actorPlayerId, actorTeamId) {
    const hit = this.findUnitByObjectIds(objectId1, objectId2);
    if (!hit) return null;
    if (hit.ownerPlayerId === actorPlayerId) return null;
    if (_isNonPlayerOwner(hit.ownerPlayerId)) return null;
    // Strict team check when both sides known. Skip allies (same team).
    if (actorTeamId != null && hit.ownerTeamId != null &&
        hit.ownerTeamId === actorTeamId) {
      return null;
    }
    return hit;
  }

  setNeutralGroups (neutralGroups, neutralGroupTree, neutralDetectionTree) {
    this.neutralGroupTree = neutralGroupTree;
    this.neutralDetectionTree = neutralDetectionTree || neutralGroupTree;
    this.neutralGroups = neutralGroups.reduce((acc, group) => {
      acc[group.uuid] = group;

      return acc;
    }, {});
  }

  // Called when a neutral group transitions from "unengaged" to "engaged"
  // (i.e. a player has right-clicked one of its creeps). Swap its bbox in
  // the detection rbush from the tight unitBounds to the wider engagedBounds
  // so subsequent fights happening 1500u outside the camp still register
  // location events. Without this, "pulled" creep camps never accrue time.
  expandNeutralDetection (group) {
    if (!this.neutralDetectionTree || !group || !group._detectionBox || !group.engagedBounds) {
      return;
    }
    const tree = this.neutralDetectionTree;
    const oldBox = group._detectionBox;
    tree.remove(oldBox);
    oldBox.minX = group.engagedBounds.minX;
    oldBox.minY = group.engagedBounds.minY;
    oldBox.maxX = group.engagedBounds.maxX;
    oldBox.maxY = group.engagedBounds.maxY;
    tree.insert(oldBox);
  }

  setGridData (gridData) {
    this.gridData = gridData;
    this.pathFinder = new PathFinder();
    this.pathFinder.setup(gridData);

    // CollisionWorld layers dynamic unit collision on top of PathFinder's
    // static grid. stampBuilding/unstampBuilding now route through here so
    // we can use per-building pathing.tga bitmaps instead of rectangles.
    this.collisionWorld = new CollisionWorld();
    this.collisionWorld.attachPathFinder(this.pathFinder);
    this.collisionWorld.loadManifest(buildingPathingManifest);
  }

  addNeutralShop (itemId, objectId1, objectId2) {
    const shopObject = { itemId, objectId1, objectId2 };

    if (!this.neutralShops.find(shop => { 
      return shop.objectId1 === objectId1 && shop.objectId2 === objectId2; })) {
      this.neutralShops.push(shopObject);
    }
  }

  getNeutralShop (shopData) {
    const { objectId1, objectId2 } = shopData;

    return this.neutralShops.find(shop => { 
      return shop.objectId1 === objectId1 && shop.objectId2 === objectId2; 
    });
  }

  addPlayerData (player) {
    const { id, units, possibleSelectList } = player;

    this.playerData[id] = {
      id: id,
      units: Array.from(units),
      possibleSelectList: Array.from(possibleSelectList)
    };
  }

  addPlayerUnit (id, unit) {
    if (!this.playerData[id]) {
      console.logger("warning - no player data for: ", id);
      console.logger("player data: ", this.playerData);
      return;
    }

    this.playerData[id].units.push(unit);
  }

  addPlayerPossibleUnit (id, unit) {
    if (!this.playerData[id]) {
      console.logger("warning - no player data for: ", id);
      return;
    }

    this.playerData[id].possibleSelectList.push(unit);
  }

  getOtherPlayerData (playerId) {
    return Object.values(this.playerData).filter(player => {
      return player.id !== playerId;
    });
  }

  findNeutralByObjectIds (objectId1, objectId2) {
    const neutralPlayer = this.playerData[NEUTRAL_PLAYER_ID];
    return neutralPlayer.units.find(unit => {
      return unit.objectId1 === objectId1 &&
             unit.objectId2 === objectId2;
    });
  }

  findPossibleNeutralUnitByPosition (targetX, targetY) {
    const MAX_MATCH_DISTANCE = 500;
    const neutralPlayer = this.playerData[NEUTRAL_PLAYER_ID];
    const closest = utils.closestToPoint(targetX, targetY, neutralPlayer.units, (unit) => {
      return unit.objectId1 == null && unit.objectId2 == null;
    });

    if (!closest) return null;

    // only match if the neutral unit is actually near the target position
    const dx = targetX - closest.currentX;
    const dy = targetY - closest.currentY;
    if (Math.sqrt(dx * dx + dy * dy) > MAX_MATCH_DISTANCE) {
      return null;
    }

    return closest;
  }

  findKnownUnitByItemAndObjectId (playerId, itemId, objectId1, objectId2) {
    return this.getOtherPlayerData(playerId).find(player => {
      return player.units.find(unit => {
        const foundUnit = unit.itemId === itemId &&
          unit.objectId1 === objectId1 &&
          unit.objectId2 === objectId2;

        return foundUnit;
      });
    });
  }

  findPossibleUnitByItemIds (playerId, itemId1, itemId2) {
    const targetUnit = { itemId1, itemId2 };
    
    return this.getOtherPlayerData(playerId).find(player => {
      return player.possibleSelectList.find(possibleUnit => {
        return utils.isEqualUnitItemId(
          targetUnit,
          possibleUnit
        );
      });
    });
  }

  findUnknownObject (objectId1, objectId2) {
    return this.unknownObjects.find(item => {
      return item.objectId1 === objectId1 &&
             item.objectId2 === objectId2;
    });
  }

  findDroppedItem (objectId1, objectId2) {
    return this.droppedItems.find(item => {
      return item.objectId1 === objectId1 &&
             item.objectId2 === objectId2;
    });
  }

  removeDroppedItem (objectId1, objectId2) {
    return this.droppedItems.filter(item => {
      return item.objectId1 === objectId1 &&
             item.objectId2 === objectId2;
    });
  }

  removeUnknownObject (objectId1, objectId2) {
    return this.unknownObjects.filter(item => {
      return item.objectId1 === objectId1 &&
             item.objectId2 === objectId2;
    });
  }

  clearKnownItem (objectId1, objectId2) {
    this.removeDroppedItem(objectId1, objectId2);
    this.removeUnknownObject(objectId1, objectId2);
  }

  addUnknownObject (objectId1, objectId2) {
    let worldKnownItem = this.findUnknownObject(objectId1, objectId2);

    if (!worldKnownItem) {
      console.logger("Adding unknown object to world.");
      let unknownUnit = new Unit(this.eventTimer, null, null, null, false);
      unknownUnit.registerObjectIds(objectId1, objectId2);

      this.unknownObjects.push(unknownUnit);
    }
  }
};

module.exports = World;
