/**
 * desktop-preview.js — render the desktop UI in an ordinary browser.
 *
 * The desktop frontend needs Tauri for everything it reads, so the only way to
 * look at it used to be to build and launch the app. This writes a
 * `preview.html` into desktop/dist that stubs the Tauri IPC with summaries
 * built from real parsed replays in client/replays — so the feed, the game
 * detail, the moments list and the profile all render against real data.
 *
 * The stub answers `read_parse` with genuinely gzipped bytes, so the app's own
 * store.js (gunzip, schema check, corpus sort) runs unmodified. What you see is
 * the real code path, not a mock of it.
 *
 * Usage:
 *   node tools/build-desktop-client.js && node tools/desktop-preview.js
 *   node tools/desktop-preview.js --games=8 --me="SooooK#31962"
 *
 * Then open desktop/dist/preview.html in a browser.
 */

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const SummaryExtract = require('../client/js/SummaryExtract');
const MomentsExtract = require('../client/js/MomentsExtract');

const ROOT = path.resolve(__dirname, '..');
const REPLAY_DIR = path.join(ROOT, 'client', 'replays');
const DIST = path.join(ROOT, 'desktop', 'dist');

const args = {};
process.argv.slice(2).forEach(raw => {
  const [flag, ...rest] = raw.replace(/^--/, '').split('=');
  args[flag] = rest.join('=') || true;
});

if (!fs.existsSync(DIST)) {
  console.error('desktop/dist does not exist. Run: node tools/build-desktop-client.js');
  process.exit(1);
}

// Mirror of desktop/src-frontend/js/store.js buildSummary. Duplicated rather
// than shared because that one is a browser module that reads window globals;
// keeping this tool free of a DOM shim is worth twenty lines.
const buildSummary = (out, key, playedAt) => {
  const rawMap = (out.replay && out.replay.metadata && out.replay.metadata.map &&
    out.replay.metadata.map.mapName) || '';
  const durationMs = (out.replay && out.replay.subheader &&
    out.replay.subheader.replayLengthMS) || 0;
  const worldNeutralGroups = (out.world && out.world.neutralGroups) || null;
  const summary = {
    key,
    schemaVersion: 2,
    savedAt: Date.now(),
    playedAt,
    patchVersion: (out.replay && out.replay.subheader && out.replay.subheader.version) || null,
    map: rawMap.split(/[\\/]/).pop(),
    mapRaw: rawMap,
    gameMode: out.gameMode || null,
    winner: out.winner || null,
    durationMs,
    neutralCamps: SummaryExtract.extractNeutralCamps(worldNeutralGroups),
    moments: MomentsExtract.extractMoments(out),
    players: {}
  };
  for (const slot of Object.keys(out.players || {})) {
    const pd = out.players[slot];
    const rpd = out.replay && out.replay.players && out.replay.players[slot];
    if (!pd || !rpd || pd.isNeutralPlayer) continue;
    if (rpd.teamId >= 1000) continue;
    summary.players[slot] = SummaryExtract.extractPlayerSummary(pd, rpd, durationMs, worldNeutralGroups);
    summary.players[slot].teamId = rpd.teamId;
  }
  return summary;
};

const wanted = parseInt(args.games, 10) || 12;
const files = fs.readdirSync(REPLAY_DIR).filter(f => f.endsWith('.wc3v.gz')).slice(0, wanted);
if (!files.length) {
  console.error(`No parsed replays in ${path.relative(ROOT, REPLAY_DIR)}`);
  process.exit(1);
}

const store = {};   // key -> base64 gzipped summary JSON
const nameCounts = new Map();
let day = Date.now();

for (const file of files) {
  let out;
  try {
    out = JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(REPLAY_DIR, file))).toString());
  } catch (e) {
    console.log(`  skipped ${file}: ${e.message}`);
    continue;
  }
  // Spread the fake play times over recent days so the feed's day grouping,
  // "Today"/"Yesterday" headers and newest-first ordering all get exercised.
  day -= Math.round((2 + Math.random() * 20) * 3600 * 1000);
  const size = fs.statSync(path.join(REPLAY_DIR, file)).size;
  const key = `${size}-${Buffer.from(file).toString('hex').slice(0, 16)}`;
  const summary = buildSummary(out, key, day);
  store[key] = zlib.gzipSync(JSON.stringify(summary)).toString('base64');
  for (const p of Object.values(summary.players)) {
    nameCounts.set(p.name, (nameCounts.get(p.name) || 0) + 1);
  }
  console.log(`  ${file} → ${(store[key].length / 1024).toFixed(1)} KB, ` +
    `${summary.moments.length} moments`);
}

// Whoever appears most often stands in for "you" — the same signal the real
// identity detection uses, which is what makes the verdicts orient correctly.
const me = (typeof args.me === 'string' && args.me) ||
  [...nameCounts.entries()].sort((a, b) => b[1] - a[1])[0][0];

const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>WC3V — preview</title></head>
<body>
<script>
// ── Tauri IPC stub ─────────────────────────────────────────────────────────
// Generated by tools/desktop-preview.js. Everything the app reads is answered
// from summaries built out of real parsed replays.
const STORE = ${JSON.stringify(store)};
const b64 = (s) => { const bin = atob(s); const a = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) a[i] = bin.charCodeAt(i); return a; };

window.__TAURI__ = {
  core: {
    invoke: async (cmd, args) => {
      switch (cmd) {
        case 'init': return { roots: [
          { path: 'X', replay_count: 3128 }, { path: 'Y', replay_count: 999 }
        ], map_cache_dir: 'X' };
        case 'list_parses': return Object.keys(STORE);
        case 'list_parse_failures': return [];
        case 'read_parse': return b64(STORE[args.key]);
        case 'scan_replays': return { replays: [], stats: { files_seen: 4875, walk_ms: 180 } };
        // One stand-in file per stored game, sized to match its content key, so
        // replay-index.js resolves key → path exactly as it does for real. Any
        // stub that returned [] would make every Watch / Open-in-viewer click
        // dead-end at "file not found", which is not what those buttons do.
        case 'scan_all': return { replays: Object.keys(STORE).map((k, i) => ({
          path: 'PREVIEW-' + i, file_name: 'Replay_' + i + '.w3g',
          size: Number(k.split('-')[0]), modified_ms: 0, key: k,
          interesting: true, autosaved: true
        })) };
        case 'replay_key': {
          const i = Number(String(args.path).replace('PREVIEW-', ''));
          return { key: Object.keys(STORE)[i], modifiedMs: 0 };
        }
        // Deliberately refuses, with the reason. The real command hands the
        // replay to the browser, which a stubbed page cannot do — saying so is
        // more useful than pretending it worked.
        case 'open_in_viewer':
          throw 'the viewer handoff needs the real app (this is the UI preview)';
        case 'start_watching': return 2;
        case 'get_autostart': return false;
        case 'publish_overlay_state': return null;
        case 'overlay_info': return { url: 'http://127.0.0.1:0/overlay?token=preview' };
        case 'check_for_update': return { status: 'unconfigured' };
        default: throw new Error('preview stub: no ' + cmd);
      }
    }
  },
  event: { listen: async () => (() => {}) },
  dialog: { open: async () => null }
};
// The app asks identity for a confirmed name; pre-answer it so the preview
// opens with verdicts already oriented instead of the picker.
localStorage.setItem('wc3v-user-name', ${JSON.stringify(me)});
localStorage.setItem('wc3v-user-name-confirmed', '1');
</script>
${fs.readFileSync(path.join(DIST, 'index.html'), 'utf8')
  .replace(/^[\s\S]*?<body>/, '')
  .replace(/<\/body>[\s\S]*$/, '')}
${
  // The preview page owns <head>, so the real page's stylesheet links are
  // re-emitted into the body (browsers accept this). Carried through by
  // reading them rather than listing them here — hardcoding the list is how
  // the preview ended up missing overlay.css and silently rendering the
  // Stream screen unstyled.
  (fs.readFileSync(path.join(DIST, 'index.html'), 'utf8')
    .match(/<link rel="stylesheet"[^>]*>/g) || []).join('\n')
}
</body></html>
`;

fs.writeFileSync(path.join(DIST, 'preview.html'), html);
console.log('');
console.log(`preview:   ${path.relative(ROOT, path.join(DIST, 'preview.html'))}`);
console.log(`games:     ${Object.keys(store).length}`);
console.log(`you:       ${me}`);
